"""Initial migration

Revision ID: 12cfaff2fdc1
Revises: 
Create Date: 2026-07-18 09:37:48.935482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12cfaff2fdc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.alter_column('EmergencyRequest', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'consumerId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'needType',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLAIMED', 'FULFILLED', name='RequestStatus'),
               nullable=True,
               existing_server_default=sa.text('\'OPEN\'::"RequestStatus"'))
    op.alter_column('EmergencyRequest', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('EmergencyRequest_consumerId_fkey'), 'EmergencyRequest', type_='foreignkey')
    op.create_foreign_key(None, 'EmergencyRequest', 'User', ['consumerId'], ['id'])
    op.alter_column('Listing', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Listing', 'farmerId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Listing', 'cropName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Listing', 'unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Listing', 'photoUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Listing', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'SOLD_OUT', 'REMOVED', name='ListingStatus'),
               nullable=True,
               existing_server_default=sa.text('\'AVAILABLE\'::"ListingStatus"'))
    op.alter_column('Listing', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('Listing_farmerId_fkey'), 'Listing', type_='foreignkey')
    op.create_foreign_key(None, 'Listing', 'User', ['farmerId'], ['id'])
    op.alter_column('NGO', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('NGO', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('NGO', 'organizationName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('NGO', 'verificationStatus',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('NGO', 'documentUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('NGO', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('NGO_userId_key'), table_name='NGO')
    op.create_unique_constraint(None, 'NGO', ['userId'])
    op.drop_constraint(op.f('NGO_userId_fkey'), 'NGO', type_='foreignkey')
    op.create_foreign_key(None, 'NGO', 'User', ['userId'], ['id'])
    op.alter_column('Order', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Order', 'consumerId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Order', 'listingId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Order', 'status',
               existing_type=postgresql.ENUM('PLACED', 'CONFIRMED', 'DELIVERED', 'CANCELLED', name='OrderStatus'),
               nullable=True,
               existing_server_default=sa.text('\'PLACED\'::"OrderStatus"'))
    op.alter_column('Order', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('Order_consumerId_fkey'), 'Order', type_='foreignkey')
    op.drop_constraint(op.f('Order_listingId_fkey'), 'Order', type_='foreignkey')
    op.create_foreign_key(None, 'Order', 'User', ['consumerId'], ['id'])
    op.create_foreign_key(None, 'Order', 'Listing', ['listingId'], ['id'])
    op.alter_column('User', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('User', 'passwordHash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('User_email_key'), table_name='User')
    op.drop_index(op.f('User_phone_key'), table_name='User')
    op.create_unique_constraint(None, 'User', ['email'])
    op.create_unique_constraint(None, 'User', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.create_index(op.f('User_phone_key'), 'User', ['phone'], unique=True)
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.alter_column('User', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('User', 'passwordHash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('User', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.create_foreign_key(op.f('Order_listingId_fkey'), 'Order', 'Listing', ['listingId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('Order_consumerId_fkey'), 'Order', 'User', ['consumerId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('Order', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Order', 'status',
               existing_type=postgresql.ENUM('PLACED', 'CONFIRMED', 'DELIVERED', 'CANCELLED', name='OrderStatus'),
               nullable=False,
               existing_server_default=sa.text('\'PLACED\'::"OrderStatus"'))
    op.alter_column('Order', 'listingId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Order', 'consumerId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Order', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'NGO', type_='foreignkey')
    op.create_foreign_key(op.f('NGO_userId_fkey'), 'NGO', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'NGO', type_='unique')
    op.create_index(op.f('NGO_userId_key'), 'NGO', ['userId'], unique=True)
    op.alter_column('NGO', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('NGO', 'documentUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('NGO', 'verificationStatus',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('NGO', 'organizationName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('NGO', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('NGO', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Listing', type_='foreignkey')
    op.create_foreign_key(op.f('Listing_farmerId_fkey'), 'Listing', 'User', ['farmerId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('Listing', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Listing', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'SOLD_OUT', 'REMOVED', name='ListingStatus'),
               nullable=False,
               existing_server_default=sa.text('\'AVAILABLE\'::"ListingStatus"'))
    op.alter_column('Listing', 'photoUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Listing', 'unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Listing', 'cropName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Listing', 'farmerId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Listing', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'EmergencyRequest', type_='foreignkey')
    op.create_foreign_key(op.f('EmergencyRequest_consumerId_fkey'), 'EmergencyRequest', 'User', ['consumerId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('EmergencyRequest', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('EmergencyRequest', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLAIMED', 'FULFILLED', name='RequestStatus'),
               nullable=False,
               existing_server_default=sa.text('\'OPEN\'::"RequestStatus"'))
    op.alter_column('EmergencyRequest', 'needType',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'consumerId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('EmergencyRequest', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    # ### end Alembic commands ###
