"""Add assignedMandi and SavedMandi

Revision ID: 5cf19c63066d
Revises: 740120dd337a
Create Date: 2026-07-26 19:50:28.962160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf19c63066d'
down_revision: Union[str, Sequence[str], None] = '740120dd337a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SavedMandi',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('mandiId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mandiId'], ['DistributionCenter.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('User', sa.Column('assignedMandiId', sa.String(), nullable=True))
    op.create_foreign_key(None, 'User', 'DistributionCenter', ['assignedMandiId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'assignedMandiId')
    op.drop_table('SavedMandi')
    # ### end Alembic commands ###
