"""Add Kitchen, EmergencyWindow, Notification, and QualityGrade

Revision ID: 740120dd337a
Revises: 802ec4780987
Create Date: 2026-07-18 22:57:03.670598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740120dd337a'
down_revision: Union[str, Sequence[str], None] = '802ec4780987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmergencyWindow',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_CONFIRMATION', 'ACTIVE', 'RESOLVED', name='windowstatus'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KitchenPartner',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('kitchenName', sa.String(), nullable=False),
    sa.Column('verificationStatus', sa.Boolean(), nullable=True),
    sa.Column('documentUrl', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('Notification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FoodPledge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kitchenId', sa.String(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'COMMITTED', 'FULFILLED', name='pledgestatus'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kitchenId'], ['KitchenPartner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Listing', sa.Column('qualityGrade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Listing', 'qualityGrade')
    op.drop_table('FoodPledge')
    op.drop_table('Notification')
    op.drop_table('KitchenPartner')
    op.drop_table('EmergencyWindow')
    # ### end Alembic commands ###
