"""Add location, category, cart, payment fields

Revision ID: 802ec4780987
Revises: 1bd60814f4de
Create Date: 2026-07-18 22:37:04.820724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802ec4780987'
down_revision: Union[str, Sequence[str], None] = '1bd60814f4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cart',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('consumerId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consumerId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumerId')
    )
    op.create_table('CartItem',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cartId', sa.String(), nullable=False),
    sa.Column('listingId', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cartId'], ['Cart.id'], ),
    sa.ForeignKeyConstraint(['listingId'], ['Listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Listing', sa.Column('location', sa.String(), nullable=True))
    
    # Create enum type before adding column
    from sqlalchemy.dialects.postgresql import ENUM
    listing_category_enum = ENUM('VEGETABLES', 'FRUITS', 'DAIRY', 'GRAINS', 'SPICES', name='listingcategory', create_type=False)
    listing_category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('Listing', sa.Column('category', listing_category_enum, nullable=True))
    
    # Add new values to OrderStatus enum
    # Commit required since ALTER TYPE cannot run inside a transaction block
    op.execute("COMMIT")
    op.execute("ALTER TYPE \"OrderStatus\" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT'")
    op.execute("ALTER TYPE \"OrderStatus\" ADD VALUE IF NOT EXISTS 'PAID'")
    
    op.add_column('Order', sa.Column('razorpayOrderId', sa.String(), nullable=True))
    op.add_column('Order', sa.Column('razorpayPaymentId', sa.String(), nullable=True))
    op.add_column('Order', sa.Column('razorpaySignature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'razorpaySignature')
    op.drop_column('Order', 'razorpayPaymentId')
    op.drop_column('Order', 'razorpayOrderId')
    op.drop_column('Listing', 'category')
    op.drop_column('Listing', 'location')
    op.drop_table('CartItem')
    op.drop_table('Cart')
    # ### end Alembic commands ###
